const subjects = [
  "Select Your Subject",
  "Website Development",
  "Mobile Apps Developemnt",
  "Website Designing",
  "Graphic Designing",
  "School Management Software - EduCareStudy",
];

const states = [
  "Select Your State",
  "Andaman & Nicobar",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chattisgarh",
  "Dadar & Nagar Haveli",
  "Daman & Due",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamilnadu",
  "Telangana",
  "Tripura",
  "Utter Pradesh",
  "Uttrakhand",
  "West Bangal",
];

export { subjects, states };
