const services = [
  {
    id: 1,
    head: "Services",
    first: "#E3436B",
    second: "#F0772F",
    children: [
      "Website Design And Development",
      "E-Commerce Website Development",
      "Mobile App Development",
      "Classified Website Development",
      "Web Portal News Paper Development",
      "Logo And Graphic Design",
      "Website Maintaince",
      "Website Template",
      "Website Hosting",
      "Email Hosting Service",
      "Website Registration",
    ],
  },
  {
    id: 2,
    head: "Software",
    first: "#9D80CB",
    second: "#F7C2E6",
    children: [
      "Software Development Servicet",
      "Human Resources Management",
      "Hospital Management Software",
      "Garments ERP",
      "Business ERP Software",
      "Garments Accessories Manufacturer ERP",
      "School Management Software",
      "Hotel Management Software",
      "Production Management Software",
      "Customer Relationship-CRM",
      "Account & Inventory Management",
      "Retail POS Software",
      "Payroll Management Software",
      "Document Management System",
    ],
  },
  {
    id: 3,
    head: "Retail POS",
    first: "#45A0EA",
    second: "#F9658E",
    children: [
      "Retail POS Software",
      "Retail-Point Of Sales (POS)- EduCare Account",
      "POS Software & App -EduCare Study",
      "Restaurant management",
      "Pharmacy Management Software",
      "Tiles Sanitary POS Software",
      "Electronics Shop POS Software",
      "Footwear POS Software",
      "ISP & Cable TV Billing",
    ],
  },
  {
    id: 4,
    head: "Mobile App",
    first: "#FFCF67",
    second: "#D3321D",
    children: [
      "App Development",
      "Online Doctor App Development",
      "Online Learning Platform Development",
      "HRM Mobile App",
      "FM Radio",
    ],
  },
  {
    id: 5,
    head: "Digital Marketing",
    first: "#FC4778",
    second: "#3952F5",
    children: [
      "Email Marketing",
      "SMS Marketing",
      "Search Engine Optimization (SEO)",
      "Social Media Marketing",
    ],
  },
  {
    id: 6,
    head: "Device",
    first: "#CCB3D1",
    second: "#22052D",
    children: [
      "Biometrics Attendance",
      "POS Device",
      "Search Engine Optimization (SEO)",
      "Social Media Marketing",
    ],
  },
];

export default services;
